// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-bro8lJmjHEEqoHfcGuNtjFDE1YOQAu0',
    appId: '1:433794825483:web:bc884cc03aa8beadf2760e',
    messagingSenderId: '433794825483',
    projectId: 'sandesh-31934',
    authDomain: 'sandesh-31934.firebaseapp.com',
    databaseURL: 'https://sandesh-31934-default-rtdb.firebaseio.com',
    storageBucket: 'sandesh-31934.appspot.com',
    measurementId: 'G-SLXH7QC06T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLUS8OOZWqPJWBsIZi2Ifg9D4LikTPzA',
    appId: '1:433794825483:android:45fe009b7a971b00f2760e',
    messagingSenderId: '433794825483',
    projectId: 'sandesh-31934',
    databaseURL: 'https://sandesh-31934-default-rtdb.firebaseio.com',
    storageBucket: 'sandesh-31934.appspot.com',
  );
}
